<div class="conteudoab">
<div class="namein">Termos de uso</div>
<div class="namein2"></div>
<div class="namein4"></div>
<textarea name="textarea1" id="textarea1" cols="90" rows="88">
Termos Mixmaster online de Uso.

-TERMOS DE ACORDO 

MixMaster Online oferece para lhe permitir desempenhar o seu multi-player do jogo de computador online "Mixmaster Online" condicionando a sua concordância com todos os termos e condições contidas no presente Acordo e sua conformidade com as Regras de Conduta postadas. O uso do Mixmaster online constitui a sua concordância com todos os termos e condições e seu contrato para cumprir com as Regras de Conduta. Se caso em que você rejeitar as condições oferecidas de uso e não será permitido jogar Mixmaster Online. Se você tiver alguma dúvida em relação a estes termos e condições ou as Regras de Conduta, entre em contato com o representante de serviço ao cliente na área de suporte do site.
MixMaster Online pode alterar o presente Acordo ou modificar as Regras de Conduta, a qualquer tempo, a seu exclusivo critério. Alterações ao Acordo será eficaz um (1) dias após o Acordo alterado é postado. As alterações das Regras de Conduta entrarão em vigor imediatamente após a publicação. Você tem o dever de verificar este Acordo e as Regras de Conduta periodicamente, assim você estará familiarizado com seu conteúdo, alterada ou modificada ao longo do tempo. 

-CONTA 

Elegibilidade. Contas estão disponíveis para todos os indivíduos. Se você deseja usar o serviço, você deve completar o processo de registro, abrir uma conta em seu nome e aceitar a plena responsabilidade por todas as obrigações sob este contrato. Aqueles que tenham concluído estes passos e que mantêm a sua conta em boas condições são muitas vezes referidos neste contrato como PLAYERS? Ao clicar no botão Cadastrar!, o usuário registrado de uma conta pode usar a conta. Apenas uma pessoa pode usar uma conta e você é responsável por todas as atividades realizadas através da conta. 

ID da conta. Na época sua Conta é aberta, você deve escolher um nome para se identificar a MixMaster Online (seu "ID de Conta"). Você não pode escolher como seu ID de Conta o nome de outra pessoa, ou um nome que viola o direito de qualquer terceiro marca registrada, direito autoral ou outro direito de propriedade, ou que possa induzir em erro os outros jogadores a acreditar que você seja um empregado de MixMaster Online, ou que MixMaster Online considere, a seu exclusivo critério a ser vulgar ou ofensivo. MixMaster Online reserva-se o direito de, a seu exclusivo critério, a apagar ou alterar qualquer ID da conta ou encerrar qualquer licença concedida, por qualquer motivo, incluindo, sem limitação, qualquer suspeita ou efetiva violação de qualquer marca registrada ou certo nome comercial, direito autoral ou outro direito de propriedade. Você tem a responsabilidade única por todas as atividades conduzidas através de sua Conta ou sob seu ID da conta. 

Conta. Ao concordar com o Contrato de Usuário, você concorda que você não possui a conta que você usa para acessar o serviço, os personagens lojas MixMaster Online em servidores MixMaster Online, os itens armazenados nesses servidores, ou quaisquer outros dados que os servidores e contas são compostos dele. A conta que você criar é necessário para acessar o serviço e a taxa que você paga é usada para você continuar a acessar o serviço. 

Nome do Personagem. Para usar o serviço, você cria um personagem e escolher um nome para o seu personagem para identificar o seu personagem para outros membros (o seu "nome do personagem"). Você não pode escolher como seu personagem Nomeie o nome de outra pessoa, ou um nome que viola marca registrada de qualquer terceiro direito, direito autoral ou outro direito de propriedade, ou que possa induzir em erro os outros jogadores a acreditar que você seja um empregado de MixMaster Online, ou que MixMaster Online julgar a seu exclusivo critério a ser vulgar ou ofensivo. MixMaster Online reserva-se o direito de, a seu exclusivo critério, a (1) apagar ou alterar qualquer nome de personagem ou (2) encerrar qualquer licença concedida, por qualquer motivo, incluindo, sem limitação, qualquer suspeita ou efetiva violação de qualquer marca registrada ou certo nome comercial, direito autoral ou outro direito de propriedade. 

As senhas. Na época sua Conta é aberta, você deve selecionar uma senha. Você é responsável por manter a confidencialidade de sua senha e você é responsável por qualquer dano resultante de sua divulgação ou permitir a divulgação de sua senha ou de uso por qualquer pessoa de sua senha para ter acesso à sua conta e ID da conta. Em nenhum momento você deve responder a uma solicitação on-line para uma senha. MixMaster Online nunca pedirá sua senha offline ou online, a não ser que você será obrigado a digitar sua senha como parte do processo de login. 
ex-membros. Usuários cujas contas tenham sido denunciado por MixMaster Online não podem acessar o serviço de qualquer maneira ou por qualquer motivo, inclusive por meio de qualquer outra Conta, sem a permissão expressa por escrito da MixMaster Online. 

Contas envolvidas. Se MixMaster Online termina uma Conta, MixMaster Online poderá rescindir quaisquer outras contas que compartilham o mesmo nome de membro, número de telefone, endereço de email, endereço postal, endereço de Internet Protocolo, ou o número do cartão de crédito com a conta encerrada. 
Downloads. Downloads do programas MixMaster Online só deve ser baixado do nosso site ou de qualquer outro site espelho que aprovamos. MixMaster Online não será responsável por qualquer dano resultante a partir do download de qualquer outro site.

MixMaster Online tem a propriedade exclusiva de todos os serviços pagos em MixMaster Online, MIXMALL, SHOP, se o usuário comprou determinados conteúdos têm o uso de certo item na web. O usuário só tem direito de uso durante o período de tempo específico quando o usuário comprar o serviço pago na MIXMALL, SHOP. 
O artigo Pago propriedade de usuário não podem ser vendidos ou transferidos a terceiros sem consentimento MixMaster Online. 
Artigo gratuito e o item dotado de outros usuários não são reembolsáveis. 
Período de utilização item de jogo é limitada ao período de serviço. MixMaster Online termina jogo prestação de serviço Mixmaster online, uso item certo será encerrada juntamente com o término do serviço. 
No caso de violar este acordo e dar algum dano a MixMaster Online, você perderá o seu direito de todos e você é totalmente responsável por todos os custos, taxas e outras despesas incorridas. 

-PRIVACIDADE 

As informações pessoais que você nos fornece durante o registro é usado apenas para nossos propósitos internos. Usamos as informações que coletamos para saber o que você gosta e para melhorar o serviço. Salvo se expressamente permitido por este Contrato ou conforme autorizado por você, não vamos dar nenhuma de suas informações pessoais para terceiros sem a sua autorização expressa. Nós não podemos garantir a segurança de qualquer de suas transmissões privadas contra interceptação não autorizada ou ilegal ou acesso por terceiros. Podemos (e você nos autoriza a) divulgar qualquer informação sobre você para entidades privadas, agências de aplicação da lei ou funcionários do governo, como nós, a nosso exclusivo critério, acreditamos necessário ou apropriado para investigar ou resolver possíveis problemas ou dúvidas, ou conforme exigido por lei. Se você solicitar qualquer suporte técnico, você concorda com a nossa acesso remoto e análise do computador que você carregar o software em para fins de suporte e depuração. Você concorda que podemos nos comunicar com você via e-mail e qualquer tecnologia similar para qualquer propósito relacionado ao Serviço, o Software e quaisquer serviços ou software que pode no futuro ser fornecidos por nós ou em nosso nome. 

- REGRAS DE CONDUTA 

Tal como acontece com todas as coisas, o uso do serviço é governado por certas regras de conduta. Estas regras de conduta mantida e executada exclusivamente por MixMaster Online, deve ser respeitado por todos os usuários do serviço. O usuário concorda em usar os Serviços somente para fins legais. MixMaster Online reserva-se o direito de rescindir usuários, uma do usuário se ele determinar, a seu exclusivo critério, que o usuário tenha uma conduta inaceitável. A lista de condutas proibidas estabelecida na Subseção a seguir fornece exemplos de conduta inaceitável, que lista não é exaustiva, e MixMaster Online reserva-se o direito, mas não a responsabilidade, de restringir conduta que MixMaster Online considere, a seu exclusivo critério, que seja prejudicial aos usuários individuais, prejudicando aos Serviços, ou em violação de MixMaster Online ou quaisquer direitos de terceiros. MixMaster Online podem proibir ou excluir conduta, comunicação ou conteúdo transmitido em serviço MixMaster Online, que é considerada em violação das leis aplicáveis ou é prejudicial para outros usuários, a comunidade de serviço MixMaster Online ou os direitos de MixMaster Online em geral. O usuário reconhece, no entanto, que a comunicação sobre os serviços muitas vezes ocorre em tempo real e MixMaster Online não podem, e não pretende, a comunicação de tela com antecedência. 

VOCÊ NÃO PODE usar os serviços para: 

A) Assediar, ameaçar ou embaraçar outro usuário dos Serviços ou para causar angústia, atenção indesejada ou desconforto de tal Usuário, ou qualquer outra pessoa ou entidade. Não MixMaster Online não tolera qualquer forma de assédio e pode suspender ou cancelar a conta de qualquer usuário que assedia outros. Ataques pessoais, como as baseadas em raça de uma pessoa, nacionalidade, etnia, religião, gênero, opção de vida, invalidez ou outro tipo de afiliação, são estritamente proibidos. 
B) Colocar ou transmitir imagens sexualmente explícitas ou ponto ou referência a tais imagens. MixMaster Online proíbe a transferência ou colocação de imagens sexualmente explícitas ou outros conteúdos considerados ofensivos. 
C) Transmitir qualquer, o conteúdo racial, étnico ou censurável ilegal, prejudicial, ameaçador, abusivo, ofensivo, difamatório, vulgar, obsceno, odioso. Se o usuário se envolve em língua vulgar ou abusiva on-line, mesmo que dissimulada por símbolos ou outros caracteres, ou se engaja em comportamento inadmissível, o usuário pode receber uma advertência ou ser temporariamente ou permanentemente excluído de um ou mais jogos, quadros de avisos, áreas de bate-papo ou usuários, uma do Usuário poderá ser rescindido imediatamente eo usuário pode estar sujeito a responsabilidade e / ou civil por parte das autoridades responsáveis pela aplicação da lei. 
D) Scroll ou realizar qualquer ação com um efeito perturbador semelhante. "Scrolling" é definido como fazendo repetidamente a tela a rolar mais rápido do que usuários sejam capazes de digitar nele. 
E) Fingir ser outra pessoa, incluindo, mas não limitado a, funcionários do MixMaster Online, monitores ou hospedeiros. O usuário não deve conter a si mesmo para fora ou retratar a si mesmo como um usuário pessoal MixMaster Online ou funcionário enquanto se envolve em todas as formas de comunicação on-line, incluindo, mas não limitado a, nomes de usuários, perfis de usuário, voz, texto ou gráfico bate-papo, postagens de mensagens ou qualquer forma de comunicação on-line. Personificação de pessoal MixMaster Online deve ser motivo para cancelamento imediato da conta. 
F) Envolver-se em "comportamento perturbador" em áreas de bate-papo, áreas de jogos, quadros de avisos, ou qualquer outra área dos Serviços. Comportamento perturbador será considerada para incluir, mas não se limitando a, conduta que intencionalmente interfere com o fluxo normal de diálogo em uma área de serviço. Comportamento perturbador deve também incluir, mas não se limitando a, publicações comerciais, solicitações e anúncios. 
G) Colocar ou transmitir correntes ou esquemas de pirâmide de marketing. Este tipo de material coloca uma carga desnecessária sobre os Serviços e é considerado um incômodo por muitos usuários. Certos tipos de correntes e esquemas de pirâmide também são ilegais. Tal conduta proibidas inclui, mas não está limitado a, o envio de cartas ou mensagens que oferecem um serviço ou produto e que são baseadas na estrutura de uma corrente. 
H) publicar ou transmitir publicidade não solicitada, materiais promocionais, ou outras formas de solicitação. Serviços MixMaster Online não devem ser usados para enviar publicidade não solicitada, material promocional, ou outras formas de solicitação a outros usuários. O usuário não pode usar os serviços MixMaster Online para coletar ou "colher" nomes de usuário sem a permissão expressa dos usuários. MixMaster Online reserva-se o direito de bloquear e / ou filtrar solicitações de e-mail em massa no ou através do serviço. 
I) Violar as regras de funcionamento, política ou diretriz de qualquer outro serviço online. Usuário concorda, ainda, a respeitar as regras do provedor de serviços de Internet do Usuário. 
J) Violar, intencionalmente ou não, qualquer, estadual, nacional ou internacional local aplicável ou regulamento. 
K) Modificar quaisquer arquivos que MixMaster Online não autorizar especificamente usuário modificar. Uso de material, que está sujeita aos direitos de qualquer pessoa ou entidade, sem a permissão expressa do detentor dos direitos tal, é proibida, e irá resultar no cancelamento de usuários, uma do Usuário e eventual responsabilidade civil e / ou criminal. 
L) Postando com muitos quadros de avisos de uma só vez e / ou o envio de vários e-mails não solicitados a um único endereço, por vezes referido como "spamming", é proibida. MixMaster Online pode tomar medidas por conta de um usuário se alguma das seguintes infracções é relatado: (a) postar uma mensagem semelhante ou idêntico a mais de 5 quadros de avisos; (b) Enviar e-mails para mais de 30 pessoas, ou (c) O envio de mais de dois (2) e-mails não solicitados a um único endereço de e-mail. Spam repetida resultará no encerramento da conta. Em determinadas situações, o padrão geral de comportamento em uma conta ou um conjunto de contas vinculadas podem ser determinados a ser perturbador ou abusivo, mesmo se há um único ato viola claramente qualquer política específica. Nesses casos, MixMaster Online reserva-se o direito de determinar quais os padrões de comportamento são definidos como "de alta manutenção" ou "disruptiva" e pode tomar medidas contra a conta (s), que vão desde um simples pedido para moderar o comportamento de alta manutenção , ao bloqueio total de todas as contas vinculadas. 

- SEGURANÇA DE INFORMAÇOES DE LOGIN 

Você é responsável por manter a confidencialidade de suas informações de login, e você será responsável por todos os usos de você Informações para o login, ou não autorizada por você. No caso em que você se torna consciente de ou razoavelmente respeitar qualquer violação de segurança, incluindo, sem limitação, qualquer perda, roubo ou divulgação não autorizada de seu login de Informações, você deve notificar imediatamente MixMaster Online. 

- INTERRUPÇAO DO SERVIÇO

MixMaster Online reserva-se o direito de interromper o serviço ao longo do tempo em uma programação regular ou de outro modo, com ou sem aviso prévio, a fim de realizar a manutenção. 

Você reconhece que o serviço pode ser interrompido por razões fora do controle da MixMaster Online e MixMaster Online não pode garantir que você será capaz de acessar o serviço ou sua conta sempre que você pode querer fazê-lo. MixMaster Online não será responsável por qualquer interrupção do Serviço, atraso ou falha na execução, resultantes de causas de qualquer natureza. 

MixMaster Online  não será obrigada a reembolsar qualquer de despesa em razão de qualquer interrupção do serviço por motivo de qualquer.
-Isenção de Garantia 

MixMaster Online FORNECE O SERVIÇO, O SOFTWARE, A CONTA, O JOGO MIXMASTER ONLINE E TODOS OS OUTROS SERVIÇOS "COMO ESTÁ", E RENUNCIA EXPRESSAMENTE TODAS AS GARANTIAS OU CONDIÇÕES DE QUALQUER TIPO, escritos ou orais, EXPRESSA OU IMPLÍCITA, INCLUINDO, SEM LIMITAÇÃO, QUALQUER GARANTIA DE TÍTULO, NÃO VIOLAÇÃO, COMERCIALIZAÇÃO, SATISFAÇÃO, PRECISÃO OU ADEQUAÇÃO A UM DETERMINADO FIM. Sem limitar o precedente, não assegurar, livre de erros, a operação segura ou livre de vírus contínua do Serviço, Software, sua Conta ou Mixmaster Online. Alguns estados não permitem a exclusão de garantias implícitas, portanto a isenção acima pode não se aplicar a você. Esta garantia lhe dá direitos legais específicos e você também pode ter outros direitos legais que variam de estado para estado. 

- LIMITAÇÃO DE RESPONSABILIDADE 

A quantidade máxima de RESPONSABILIDADE MixMaster Online ao abrigo deste acordo não deverá exceder o montante dos honorários conta paga POR VOCÊ À MixMaster Online. EM HIPÓTESE ALGUMA A MixMaster Online, nem nenhum dos seus fornecedores de conteúdo, acionistas, parceiros, afiliados, diretores, executivos, funcionários, agentes ou fornecedores, SERÁ RESPONSÁVEL POR VOCÊ OU QUALQUER TERCEIRO POR QUAISQUER DANOS ESPECIAIS, incidental PUNITIVOS OU EXEMPLARES , (INCLUINDO, SEM LIMITAÇÃO, PERDA DE LUCROS, INTERRUPÇÃO DE NEGÓCIOS, PERDA DE INFORMAÇÕES COMERCIAIS OU QUALQUER OUTRA PERDA PECUNIÁRIA), INDEPENDENTEMENTE DA TEORIA DE RESPONSABILIDADE (INCLUINDO CONTRATO, NEGLIGÊNCIA OU RESPONSABILIDADE OBJETIVA) DECORRENTES DE OU EM CONEXÃO COM O SERVIÇO, O SOFTWARE, SUA CONTA OU ESTE ACORDO QUE PODEM SER SOFRIDO POR VOCÊ, MESMO SEEDC PACIFIC PODEM TER SIDO AVISADO QUE TAIS DANOS pode ou poderia ocorrer. Alguns estados não permitem as limitações de responsabilidade, portanto, podem não se aplicar a você e, nesse caso, você concorda que a responsabilidade e do MixMaster Online para você será limitado ao limite máximo permitido por lei. Você concorda que MixMaster Online não pode ser considerado responsável por qualquer coisa que ocorra ou resulte do acesso ou assinatura do serviço Mixmaster Online. 

- INDENIZAÇÃO 

Você concorda em indenizar, defender e isentar MixMaster Online e suas subsidiárias e afiliadas e seus respectivos conselheiros, diretores, acionistas, funcionários, agentes, prestador de serviços clientes, clientes e prestadores de serviços de e contra qualquer perda, reclamação, demanda, custos e despesas (incluindo honorários advocatícios razoáveis) reivindicados por quaisquer terceiros devido ou resultantes de ou em conexão com o uso ou conduta no serviço, seu conteúdo, sua violação dos Termos de Acordo ou a sua violação de quaisquer direitos de outro usuário. MixMaster Online se reserva o direito de assumir a defesa exclusiva eo controle de qualquer assunto sujeito a indenização por você, que não deve desculpar as suas obrigações de indenização. 

-RESCISÃO 

Ou você ou MixMaster Online pode encerrar sua conta a qualquer momento, sem obrigação adicional para o outro. Além disso, MixMaster Online reserva-se o direito de cancelar o serviço a qualquer momento, sem mais obrigação para com você. Se o serviço ou sua conta é encerrado ou cancelado a qualquer momento, por qualquer motivo, você concorda com o seguinte: (1) você não terá direito a qualquer reembolso ou rateio de quaisquer taxas; (2) você perderá quaisquer avatares desenvolvidos ou itens acumulados e você não terá o direito de transferir, vender ou ceder quaisquer avatares ou itens para qualquer outra pessoa; (3) você não pode acessar o serviço de qualquer maneira ou por qualquer motivo, inclusive por meio de qualquer outra conta, no caso em que uma conta é encerrada, MixMaster Online pode encerrar qualquer e todas as outras contas que compartilham o nome do membro, número de telefone, endereço de e-mail, endereço de protocolo de internet ou número de cartão de crédito com a conta encerrada; (4) que pode rescindir este Contrato (incluindo sua licença de Software e sua Conta) imediatamente e sem aviso prévio em caso de violação do presente Acordo ou propositadamente infringir quaisquer terceiros direitos de propriedade intelectual, ou se não formos capazes de verificar ou autenticar qualquer informação que você fornecer para nós, ou em cima de jogo, bate-papo ou qualquer outra atividade qualquer jogador que é, a nosso exclusivo critério, inadequada e / ou em desacordo com o espírito de MixMaster Online, conforme descrito nas Regras de Conduta. Se rescindir este Contrato sob quaisquer circunstâncias, você perderá o acesso à sua conta do saldo de qualquer período pré-pago, sem qualquer reembolso. 

-DISPOSIÇÕES GERAIS 

O fracasso da MixMaster Online ou de Prestadores de Serviço de exercer os seus direitos ou insistir na execução de obrigação do usuário abaixo, não constituirá uma renúncia ou desistência daqueles ou de quaisquer outros direitos de acordo com os Termos de Acordo. 
Se qualquer disposição dos Termos de Acordo for considerada por um tribunal de jurisdição competente como inválida, as partes concordam que o tribunal deverá tentar dar efeito às intenções partes como refletido na disposição e as outras disposições dos Termos de Acordo devem continuar a ser vinculativos e permanecerá em pleno vigor e efeito. 
Os termos do acordo, juntamente com qualquer separado por escrito ou on-line acordo entre você, MixMaster Online e / ou de Prestadores de Serviço (incluindo, mas não se limitando ao Contrato de Conteúdo Adulto se aplicável a você) constituem e só o acordo, e substitui qualquer acordos anteriores entre você, de Prestadores de Serviço MixMaster Online e / ou, (incluindo, mas não se limitando a todas as versões anteriores do Contrato de Usuário, Termos gerais de Uso, e os Termos de Acordo, quando aplicável). 
Os Termos de Acordo e do relacionamento entre você, de Prestadores de Serviço MixMaster Online e / ou serão regidos e interpretados de acordo com as leis do pais, e essas partes concordam em submeter-se à jurisdição de tais tribunais. 
Você concorda que, independentemente de qualquer estatuto ou lei em contrário, qualquer ação, processo ou procedimento decorrente ou relacionado ao uso do Serviço ou dos Termos de Acordo deve ser iniciada dentro de 1 ano após tal reclamação ou causa de ação, ou ser impedida para sempre. 
Títulos das seções dos Termos de Acordo são apenas para conveniência e não têm qualquer efeito ou significado legal ou contratual. 
É o desejo expresso das partes que os Termos de Acordo e todos os documentos relacionados foram elaborados em Inglês. 

- AVISO 

Avisos podem ser enviadas para você ou você pode enviar avisos para MixMaster Online, quer através de e-mail ou correio normal. O serviço também pode fornecer notificação de quaisquer alterações aos Termos de Acordo ou outros assuntos relativos ao Serviço, exibindo avisos ou links para avisos em geral no Serviço. 

- VIOLAÇOES

Por favor relate quaisquer violações dos Termos de Acordo para o nosso departamento de conformidade.

</textarea>
<div class="topbt2">
  <a href="#topbt" class="btbtbt">Voltar ao topo</a>
</div>
</div>